[package]
name = "problem23"
version = "0.1.0"
authors = ["Daniel Martin <fizbin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "^0.21"
num-integer = "0.1.44"
funty = "1.2.0"
